from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views as v
from .forms import StudentPasswordResetForm

urlpatterns = [
    path("", v.home, name="home"),
    path("register/", v.register, name="register"),
    path("register/submitted/", v.registration_submitted, name="registration_submitted"),
    path("register/verify/<int:pk>/", v.verify_registration, name="verify_registration"),
    path("register/verify/<int:pk>/resend/", v.resend_registration_otp, name="resend_registration_otp"),
    path("login/", v.RoleLoginView.as_view(), name="login"),
    path("password-reset/", auth_views.PasswordResetView.as_view(
        form_class=StudentPasswordResetForm,
        template_name="registration/password_reset_form.html",
        email_template_name="registration/password_reset_email.txt",
        subject_template_name="registration/password_reset_subject.txt",
    ), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(
        template_name="registration/password_reset_done.html",
    ), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="registration/password_reset_confirm.html",
    ), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
        template_name="registration/password_reset_complete.html",
    ), name="password_reset_complete"),
    path("logout/", LogoutView.as_view(), name="logout"),

    path("admin/dashboard/", v.admin_dashboard, name="admin_dashboard"),
    path("admin/hr-users/add/", v.admin_hr_user_add, name="admin_hr_user_add"),
    path("admin/students/add/", v.admin_student_add, name="admin_student_add"),
    path("admin/calendar/", v.admin_calendar, name="admin_calendar"),
    path("admin/interviews/", v.admin_interviews, name="admin_interviews"),
    path("admin/interviews/export/", v.admin_interviews_export, name="admin_interviews_export"),
    path("admin/interviews/<int:pk>/quick/", v.admin_interview_quick, name="admin_interview_quick"),
    path("admin/interviews/<int:pk>/notes/", v.admin_interview_notes, name="admin_interview_notes"),
    path("student/interviews/<int:pk>/quick/", v.interview_quick, name="student_interview_quick"),
    path("admin/courses/", v.admin_courses, name="admin_courses"),
    path("admin/courses/new/", v.admin_course_add, name="admin_course_add"),
    path("admin/courses/<int:pk>/edit/", v.admin_course_edit, name="admin_course_edit"),
    path("admin/courses/<int:pk>/preview/", v.admin_course_preview, name="admin_course_preview"),
    path("admin/reports/", v.admin_reports, name="admin_reports"),
    path("admin/mock-reviews/", v.admin_mock_interviews, name="admin_mock_interviews"),
    path("admin/mock-reviews/export/", v.admin_mock_interviews_export, name="admin_mock_interviews_export"),
    path("admin/mock-reviews/report/", v.admin_mock_interviews_report, name="admin_mock_interviews_report"),
    path("admin/question-bank/", v.admin_questions, name="admin_questions"),
    path("admin/question-bank/new/", v.admin_question_add, name="admin_question_add"),
    path("admin/question-bank/import/", v.admin_questions_import, name="admin_questions_import"),
    path("admin/question-bank/export/", v.admin_questions_export, name="admin_questions_export"),
    path("admin/question-bank/<int:pk>/edit/", v.admin_question_edit, name="admin_question_edit"),
    path("admin/question-bank/<int:pk>/delete/", v.admin_question_delete, name="admin_question_delete"),
    path("admin/registrations/pending-count/", v.registrations_pending_count, name="registrations_pending_count"),
    path("admin/registrations/", v.admin_registrations, name="admin_registrations"),
    path("admin/registrations/<int:pk>/approve/", v.registration_approve, name="registration_approve"),
    path("admin/registrations/<int:pk>/reject/", v.registration_reject, name="registration_reject"),
    path("admin/students/", v.admin_students, name="admin_students"),
    path("admin/students/<int:pk>/", v.admin_student_detail, name="admin_student_detail"),
    path("admin/students/<int:pk>/reset-password/", v.admin_student_reset_password, name="admin_student_reset_password"),
    path("admin/students/<int:pk>/delete/", v.student_delete, name="student_delete"),
    path("admin/groups/", v.admin_groups, name="admin_groups"),
    path("admin/groups/new/", v.admin_group_add, name="admin_group_add"),
    path("admin/groups/<int:pk>/edit/", v.admin_group_edit, name="admin_group_edit"),
    path("admin/groups/<int:pk>/", v.admin_group_detail, name="admin_group_detail"),
    path("admin/groups/<int:pk>/members/add/", v.admin_group_member_add, name="admin_group_member_add"),
    path("admin/groups/<int:pk>/delete/", v.group_delete, name="group_delete"),
    path("admin/groups/<int:pk>/members/<int:student_id>/remove/", v.member_remove, name="member_remove"),

    path("student/dashboard/", v.student_dashboard, name="student_dashboard"),
    path("hr/students/", v.hr_students, name="hr_students"),
    path("student/mock-interview/", v.student_mock_interview, name="student_mock_interview"),
    path("student/mock-interview/ai/", v.student_mock_interview_ai, name="student_mock_interview_ai"),
    path("student/courses/", v.student_courses, name="student_courses"),
    path("student/interview-questions/", v.student_interview_questions, name="student_interview_questions"),
    path("cron/purge-mock-data/", v.cron_purge_mock_data, name="cron_purge_mock_data"),
    path("student/notes/", v.student_notes, name="student_notes"),
    path("student/notes/<int:pk>/reply/", v.student_note_reply, name="student_note_reply"),
    path("student/calendar/", v.student_calendar, name="student_calendar"),
    path("student/interviews/", v.student_interviews, name="student_interviews"),
    path("student/interviews/<int:pk>/notes/", v.interview_notes, name="interview_notes"),
    path("student/rounds/<int:pk>/schedule/", v.round_schedule, name="round_schedule"),
    path("student/interviews/new/", v.student_interview_add, name="student_interview_add"),
    path("student/interviews/<int:pk>/", v.student_interview_detail, name="student_interview_detail"),
    path("student/interviews/<int:pk>/edit/", v.student_interview_edit, name="student_interview_edit"),
    path("student/interviews/<int:pk>/progress/", v.student_interview_progress, name="student_interview_progress"),
    path("student/interviews/<int:pk>/status/", v.interview_status, name="interview_status"),
    path("student/interviews/<int:pk>/delete/", v.interview_delete, name="interview_delete"),
    path("student/interviews/<int:pk>/rounds/add/", v.round_add, name="round_add"),
    path("student/rounds/<int:pk>/update/", v.round_update, name="round_update"),
    path("admin/interviews/<int:pk>/", v.admin_interview_detail, name="admin_interview_detail"),
]
