# Generated by Django 4.2.30 on 2026-10-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_mockinterviewsession_mockinterviewscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewscore',
            name='answer_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mockinterviewscore',
            name='camera_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mockinterviewscore',
            name='screen_feedback',
            field=models.TextField(blank=True),
        ),
    ]
