# Generated by Django 4.2.30 on 2026-10-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_mockinterviewscore_answer_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewscore',
            name='question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mockinterviewscore',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='expected_answers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mockinterviewscore',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
