# Generated by Django 4.2.30 on 2026-10-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_user_is_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='verification_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='verification_resend_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
