# Generated by Django 4.2.30 on 2026-10-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_user_student_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='department',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='graduation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='hometown',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='parent_mobile_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='parent_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='referred_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentregistrationrequest',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
