# Generated by Django 4.2.30 on 2026-10-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_registration_student_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewsession',
            name='integrity_events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
