# Generated by Django 4.2.30 on 2026-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_fill_interview_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('kind', models.CharField(choices=[('concept', 'Concept (spoken)'), ('coding', 'Coding')], default='concept', max_length=10)),
                ('language', models.CharField(blank=True, choices=[('', 'Topic default'), ('python', 'Python'), ('sql', 'SQL'), ('pyspark', 'PySpark')], max_length=10)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['topic', 'difficulty', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='difficulty',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
