# Generated by Django 4.2.30 on 2026-10-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_seed_mock_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='prep_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
