# Generated by Django 4.2.30 on 2026-10-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_interview_prep_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewsession',
            name='events_purged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='integrity_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
