# Generated by Django 4.2.30 on 2026-10-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_mock_retention'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='time_of_interview',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
