# Generated by Django 4.2.30 on 2026-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_interview_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='attendance',
            field=models.CharField(blank=True, choices=[('attended', 'Attended'), ('no_show', 'No-show'), ('rescheduled', 'Rescheduled')], max_length=15),
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(blank=True, choices=[('walk_in', 'Walk-in'), ('campus_drive', 'Campus drive'), ('off_campus', 'Off-campus'), ('referral', 'Referral'), ('hr_call', 'HR call')], max_length=20),
        ),
        migrations.AddField(
            model_name='interview',
            name='notes_visible_to_student',
            field=models.BooleanField(default=False),
        ),
    ]
