# Generated by Django 4.2.30 on 2026-10-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_interview_type_attendance_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='round_type',
            field=models.CharField(blank=True, choices=[('aptitude', 'Aptitude / online test'), ('coding', 'Coding round'), ('technical', 'Technical interview'), ('group_discussion', 'Group discussion'), ('managerial', 'Managerial round'), ('hr', 'HR round'), ('assignment', 'Assignment'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='interviewround',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
