# Generated by Django 4.2.30 on 2026-10-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_round_type_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewround',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
