# Generated by Django 4.2.30 on 2026-10-08 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_notes(apps, schema_editor):
    Interview = apps.get_model("tracker", "Interview")
    Note = apps.get_model("tracker", "InterviewNote")
    for iv in Interview.objects.exclude(admin_notes=""):
        Note.objects.create(interview=iv, text=iv.admin_notes, visible_to_student=iv.notes_visible_to_student)


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_round_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('visible_to_student', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_notes', to='tracker.interview')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(copy_notes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='interview',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='notes_visible_to_student',
        ),
    ]
