# Generated by Django 4.2.30 on 2026-10-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0028_note_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewnotereply',
            name='seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
