# Generated by Django 4.2.30 on 2026-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_reply_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewscore',
            name='answer_transcript',
            field=models.TextField(blank=True),
        ),
    ]
