# Generated by Django 4.2.30 on 2026-10-09 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_mockinterviewscore_answer_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('batch', models.CharField(blank=True, max_length=40)),
                ('company', models.CharField(max_length=150)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
    ]
