# Generated by Django 4.2.30 on 2026-10-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0034_attendance_and_leave'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='tracker_att_date_4a8978_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewstatus',
            index=models.Index(fields=['final_status', 'updated_at'], name='tracker_int_final_s_17feae_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['status', 'start_date'], name='tracker_lea_status_13f979_idx'),
        ),
        migrations.AddIndex(
            model_name='placedstudent',
            index=models.Index(fields=['company'], name='tracker_pla_company_544a65_idx'),
        ),
        migrations.AddIndex(
            model_name='selection',
            index=models.Index(fields=['created_at'], name='tracker_sel_created_670622_idx'),
        ),
    ]
