# Generated by Django 4.2.30 on 2026-10-10 06:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0038_attendance_location_login_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='auto_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_outside_geofence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='distance_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='outside_geofence',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_lat', models.FloatField(blank=True, null=True)),
                ('centre_lng', models.FloatField(blank=True, null=True)),
                ('radius_m', models.PositiveIntegerField(default=200)),
                ('block_outside', models.BooleanField(default=False)),
                ('late_after', models.TimeField(default=datetime.time(10, 0))),
                ('auto_close_at', models.TimeField(default=datetime.time(18, 0))),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
