# Generated by Django 5.2.18 on 2026-10-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0039_attendance_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewscore',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mockinterviewscore',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewscore',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewscore',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterviewscore',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MockQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=120)),
                ('difficulty', models.CharField(default='medium', max_length=10)),
                ('questions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['topic', 'difficulty', '-id'],
                'indexes': [models.Index(fields=['topic', 'difficulty', 'is_active'], name='tracker_moc_topic_8db302_idx')],
            },
        ),
        migrations.AddField(
            model_name='mockinterviewsession',
            name='question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='tracker.mockquestionset'),
        ),
    ]
