# Generated by Django 5.2.18 on 2026-10-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0040_mock_scoring_queue_and_question_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockinterviewsession',
            name='end_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
